### PR TITLE
platform/jn5148: Fix `heap_location` naming of the platform files.

### PR DESCRIPTION
**Pull request by felipe-lavratti**

### CODE REVIEW

**Comment by TeVeDe** [comment]
Hi Felipe,

We used the solution to modify one of the files in the toolchain. See below:

 

The following fix needs to be made:
Edit: C:\NXP\bstudio_nxp\sdk\JN-SW-4163\Chip\JN5168\Build\AppBuildEnd_JN5168.ld.

Remove underscore of _heap_location in line: 
PROVIDE(heap_location  = u32HeapStart);

 





 


JN5168 tools installation for Contiki 3.x – 3

 

Your solution also fixes this, but has the advantage that we can use the tools without modification. 

 

Best Regards,

Theo van Daele

**Comment by simonduq** [comment]
@TeVeDe which do you think is the best fix? Are we expecting a next toolchain release soon, with the new name for this variable? If not it's probably best to apply this fix.

**Comment by NxpChrisGray** [comment]
Hello,

The toolchain itself is not due an update, but the SDK (JN-SW-4163) has been updated and will shortly be appearing on the website (http://www.nxp.com/techzones/wireless-connectivity/ieee802-15-4.html).

The updated toolchain, in common with other GCC implementations, removed the implicit underscore from symbols in C code which improved self-consistency (the underscore was never implied in assembler or linker scripts) but created a backwards-compatibility headache. Our ‘solution’ is to declare both heap_location and _heap_location in AppBuildEnd.ld, so one or the other will work depending on the toolchain being used.

Best regards,
Chris.

**Comment by simonduq** [comment]
OK let's stick to the non underscored version then, I'll close, please shout if you want the-reopened.

**Comment by felipe-lavratti** [comment]
Of course I didn't realize it was sdk related. Thanks for your reply. 



—

**Pull request closed without merging**
